export const authLoginConstants = {
 LOGIN_EMAIL_AND_PASSWORD: "LOGIN_EMAIL_AND_PASSWORD",
 LOGIN_MOBILE_AND_OTP: "LOGIN_MOBILE_AND_OTP",
 LOGIN_EMAIL_AND_OTP: "LOGIN_EMAIL_AND_OTP",
 LOGIN_FACEBOOK: "LOGIN_FACEBOOK",
 LOGIN_GOOGLE: "LOGIN_GOOGLE",
 LOGIN_APPLE: "LOGIN_APPLE",
 GENERATE_OTP: "GENERATE_OTP",
 MATCH_OTP: "MATCH_OTP"
}




