import { userTypesConstants } from "./userConstants";

export const userInputNames = [
    {
        type: "text",
        value: "fname",
        label: "First Name",
    },
    {
        type: "text",
        value: "lname",
        label: "Last Name",
    },
    {
        type: "phone_ext",
        value: "mobile",
        label: "Phone Number",
    },
    {
        type: "date",
        value: "dob",
        label: "Date of Birth",
    },
    {
        type: "email",
        value: "email",
        label: "Email",
    },
    {
        type: "select",
        value: "gender",
        label: "Gender",
        moduleName: [{ name: "Female", value: "Female" }, { name: "Male", value: "Male" },],
        row: true,
        style: "w-[60%]",
    },
    {
        type: "textarea",
        value: "address1",
        label: "Address 1",
        row : true,
    },
    {
        type: "textarea",
        value: "address2",
        label: "Address 2",
        row : true,
    },
    {
        type: "text",
        value: "house_no",
        label: "House No",
    },
    {
        type: "number",
        value: "postal_code",
        label: "Pin code",
    },
    {
        type: "textarea",
        value: "bio",
        label: "Bio",
        row : true,
    },
];


export const userInputDetails = [
    {
        type: "text",
        value: "username",
        label: "User Name",
    },
    {
        type: "select",
        value: "user_role",
        label: "User Role",
        moduleName: [{ name: "Customer", value: "customer" }, { name: "Admin", value: "admin" },],
        row: true,
        style: "w-[60%]",
        
    },
    {
        type: "url",
        value: "user_avatar",
        label: "User Avatar",
    },
    {
        type: "url",
        value: "user_cover",
        label: "User Cover",
    },
    {
        type: "select",
        value: "is_wp_user",
        label: "Is_wp User",
        moduleName: [{ name: "Old", value: "old" }, { name: "New", value: "new" },],
        row: true,
        style: "w-[60%]",
    },
    {
        type: "text",
        value: "company_name",
        label: "Company Name",
    },
    {
        type: "select",
        value: "email_verified",
        label: "Email Verified",
        moduleName: [{ name: "Yes", value: 1 }, { name: "No", value: 0 },],
        row: true,
        style: "w-[60%]",
        optionName:"--Select Yes or No--",
    },
    {
        type: "select",
        value: "mobile_verified",
        label: "Mobile Verified",
        moduleName: [{ name: "Yes", value: 1 }, { name: "No", value: 0 },],
        row: true,
        style: "w-[60%]",
        optionName:"--Select Yes or No--",
    },

    {
        type: "url",
        value: "facebook",
        label: "Facebook",
    },
    {
        type: "url",
        value: "youtube",
        label: "Youtube",
    },
    {
        type: "url",
        value: "apple",
        label: "Apple",
    },
    {
        type: "url",
        value: "linkedIn",
        label: "LinkedIn",
    },
    {
        type: "url",
        value: "twitter",
        label: "Twitter",
    },
    {
        type: "url",
        value: "instagram",
        label: "Instagram",
    },
];

export const userInputStatus = [
    {
        type: "select",
        value: "amount_paid",
        label: "Amount Paid",
        moduleName: [{ name: "Yes", value: 1 }, { name: "No", value: 0 },],
        row: true,
        style: "w-[60%]",
        optionName : "--Select Amount status--"
    },
];


export const UserFormList = [
    {
        id: 1,
        type: "text",
        label: "First Name",
        apiKey: "fname",
        optionsList: "",
        className : "ml-4",
        required : true,
    },
    {
        id: 2,
        type: "text",
        label: "Last Name",
        apiKey: "lname",
        optionsList: "",
        className : "ml-4",
        required : true,
    },
    {
        id: 3,
        type: "password",
        label: "Password",
        apiKey: "password",
        optionsList: "",
        required : true,
    },
    {
        id: 4,
        type: "date",
        label: "DOB",
        apiKey: "dob",
        optionsList: "",
        required : true,
    },
    {
        id: 5,
        type: "text",
        label: "User Name",
        apiKey: "username",
        optionsList: "",
        required : true,
    },
    {
        id: 6,
        type: "email",
        label: "Email",
        apiKey: "email",
        optionsList: "",
        required : true,
    },
    {
        id: 25,
        type: "phone_ext",
        label: "Phone Number",
        apiKey: "mobile",
        optionsList: "",
        column : true,
        required : true,
    },
    {
        id: 8,
        type: "select",
        label: "Gender",
        apiKey: "gender",
        className:"space-x-16",
        labelStyle : "ml-16",
        required : true,
        optionsList: [
            {
                id: 1,
                optionValue: userTypesConstants.USER_MALE,
                name: "Male",
            },
            {
                id: 2,
                optionValue: userTypesConstants.USER_FEMALE,
                name: "Female",
            },
        ],
    },
    {
        id: 9,
        type: "select",
        label: "Role",
        apiKey: "user_role",
        required : true,
        optionsList: [
            {
                id: 1,
                optionValue: userTypesConstants.USER_ROLE_CUSTOMER,
                name: "Customer",
            },
            {
                id: 2,
                optionValue: userTypesConstants.USER_ROLE_ADMIN,
                name: "Admin",
            },
            {
                id: 3,
                optionValue: userTypesConstants.USER_ROLE_HOST,
                name: "Host",
            },
            {
                id: 4,
                optionValue: userTypesConstants.USER_ROLE_CO_HOST,
                name: "Co-host",
            },
        ],
    },
    {
        id: 10,
        type: "select",
        label: "Is wp User",
        apiKey: "is_wp_user",
        required : true,
        optionsList: [
            {
                id: 1,
                optionValue: "old",
                name: "Old",
            },
            {
                id: 2,
                optionValue: "new",
                name: "New",
            },
        ],
    },
    {
        id: 11,
        type: "text",
        label: "Company Name",
        apiKey: "company_name",
        required : true,
        optionsList: "",
    },
    {
        id: 12,
        type: "text",
        label: "Address 1",
        apiKey: "address1",
        optionsList: "",
        required : true,
    },
    {
        id: 13,
        type: "text",
        label: "Address 2",
        apiKey: "address2",
        optionsList: "",
        required : false,
    },
    {
        id: 14,
        type: "text",
        label: "House No",
        apiKey: "house_no",
        optionsList: "",
        required : false,
    },
    {
        id: 15,
        type: "text",
        label: "User Avatar",
        apiKey: "user_avatar",
        optionsList: "",
        required : false,
    },
    {
        id: 16,
        type: "text",
        label: "User_Cover",
        apiKey: "user_cover",
        optionsList: "",
        required : false,
    },
    {
        id: 17,
        type: "select",
        label: "Email verified",
        apiKey: "email_verified",
        required : true,
        optionsList: [
            {
                id: 1,
                optionValue: 1,
                name: "Yes",
            },
            {
                id: 2,
                optionValue: 2,
                name: "No",
            },
        ],
    },
    {
        id: 18,
        type: "select",
        label: "Mobile verified",
        apiKey: "mobile_verified",
        required : true,
        optionsList: [
            {
                id: 1,
                optionValue: 1,
                name: "Yes",
            },
            {
                id: 2,
                optionValue: 2,
                name: "No",
            },
        ],
    },
    {
        id: 19,
        type: "text",
        label: "Facebook",
        apiKey: "facebook",
        optionsList: "",
        required : false,
    },
    {
        id: 20,
        type: "text",
        label: "Youtube",
        apiKey: "youtube",
        optionsList: "",
        required : false,
    },
    {
        id: 21,
        type: "text",
        label: "Apple",
        apiKey: "apple",
        optionsList: "",
        required : false,
    },
    {
        id: 22,
        type: "text",
        label: "Twitter",
        apiKey: "twitter",
        optionsList: "",
        required : false,
    },
    {
        id: 23,
        type: "text",
        label: "Instagram",
        apiKey: "instagram",
        optionsList: "",
        required : false,
    },
    {
        id: 24,
        type: "text",
        label: "LinkedIn",
        apiKey: "linkedIn",
        optionsList: "",
        required : false,
    },
    {
        id: 7,
        type: "textarea",
        label: "Bio",
        apiKey: "bio",
        optionsList: "",
        className:"w-[30%]",
        required : false,
    },
];

export const UserFormEditList = [
    {
        id: 1,
        type: "text",
        label: "First Name",
        apiKey: "fname",
        optionsList: "",
        required : true,
    },
    {
        id: 2,
        type: "text",
        label: "Last Name",
        apiKey: "lname",
        optionsList: "",
        required : true,
    },
    // {
    //     id: 3,
    //     type: "password",
    //     label: "Password",
    //     apiKey: "password",
    //     optionsList: "",
    // },
    {
        id: 3,
        type: "date",
        label: "DOB",
        apiKey: "dob",
        optionsList: "",
        required : true,
    },
    {
        id: 4,
        type: "text",
        label: "User Name",
        apiKey: "username",
        optionsList: "",
        required : true,
    },
    {
        id: 5,
        type: "email",
        label: "Email",
        apiKey: "email",
        optionsList: "",
        required : true,
    },
    {
        id: 7,
        type: "select",
        label: "Gender",
        apiKey: "gender",
        required : true,
        optionsList: [
            {
                id: 1,
                optionValue: userTypesConstants.USER_MALE,
                name: "Male",
            },
            {
                id: 2,
                optionValue: userTypesConstants.USER_FEMALE,
                name: "Female",
            },
        ],
    },
    {
        id: 8,
        type: "select",
        label: "User Role",
        apiKey: "user_role",
        required : true,
        // className : "w-[45%]",
        optionsList: [
            {
                id: 1,
                optionValue: userTypesConstants.USER_ROLE_CUSTOMER,
                name: "Customer",
            },
            {
                id: 2,
                optionValue: userTypesConstants.USER_ROLE_ADMIN,
                name: "Admin",
            },
            {
                id: 3,
                optionValue: userTypesConstants.USER_ROLE_HOST,
                name: "Host",
            },
            {
                id: 4,
                optionValue: userTypesConstants.USER_ROLE_CO_HOST,
                name: "Co-host",
            },
        ],
    },
    {
        id: 9,
        type: "phone_ext",
        label: "Phone Number",
        apiKey: "mobile",
        optionsList: "",
        required : true,
        // className:"w-[230%]",
        column : true,
    },
    {
        id: 6,
        type: "textarea",
        label: "Bio",
        apiKey: "bio",
        required : true,
        optionsList: "",
    },
]

